services:
  postgres:
    image: postgres:16
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: fency
      POSTGRES_PASSWORD: fency
      POSTGRES_DB: fency_react_examples
    volumes:
      - fency_react_examples_pg:/var/lib/postgresql/data

volumes:
  fency_react_examples_pg:
